# Module dependencies
function_2p_m1m2.o: function_2p0m_1mi.o
function_2p_m1m2.lo: function_2p0m_1mi.lo
function_2p_m1m2.obj: function_2p0m_1mi.obj
generic_function_2p.o: function_2p0m_1mi.o function_2p_m1m2.o
generic_function_2p.lo: function_2p0m_1mi.lo function_2p_m1m2.lo
generic_function_2p.obj: function_2p0m_1mi.obj function_2p_m1m2.obj
