# Module dependencies
options.o: precision.o
options.lo: precision.lo
options.obj: precision.obj
constants.o: precision.o
constants.lo: precision.lo
constants.obj: precision.obj
kinematic.o: precision.o
kinematic.lo: precision.lo
kinematic.obj: precision.obj
ltest.o: precision.o
ltest.lo: precision.lo
ltest.obj: precision.obj
maccu.o: precision.o
maccu.lo: precision.lo
maccu.obj: precision.obj
madds.o: constants.o mfunctions.o notfirst.o options.o precision.o
madds.lo: constants.lo mfunctions.lo notfirst.lo options.lo precision.lo
madds.obj: constants.obj mfunctions.obj notfirst.obj options.obj precision.obj
mcgs.o: precision.o
mcgs.lo: precision.lo
mcgs.obj: precision.obj
mfunctions.o: constants.o precision.o
mfunctions.lo: constants.lo precision.lo
mfunctions.obj: constants.obj precision.obj
mgetbase.o: constants.o mfunctions.o precision.o
mgetbase.lo: constants.lo mfunctions.lo precision.lo
mgetbase.obj: constants.obj mfunctions.obj precision.obj
mgetc1.o: constants.o mfunctions.o mglobal.o mrestore.o options.o precision.o
mgetc1.lo: constants.lo mfunctions.lo mglobal.lo mrestore.lo options.lo \
	precision.lo
mgetc1.obj: constants.obj mfunctions.obj mglobal.obj mrestore.obj options.obj \
	precision.obj
mgetc2.o: constants.o mfunctions.o mglobal.o mrestore.o options.o precision.o
mgetc2.lo: constants.lo mfunctions.lo mglobal.lo mrestore.lo options.lo \
	precision.lo
mgetc2.obj: constants.obj mfunctions.obj mglobal.obj mrestore.obj options.obj \
	precision.obj
mgetc3.o: constants.o mfunctions.o mglobal.o mrestore.o options.o precision.o
mgetc3.lo: constants.lo mfunctions.lo mglobal.lo mrestore.lo options.lo \
	precision.lo
mgetc3.obj: constants.obj mfunctions.obj mglobal.obj mrestore.obj options.obj \
	precision.obj
mgetc4.o: constants.o mfunctions.o mglobal.o mrestore.o options.o precision.o
mgetc4.lo: constants.lo mfunctions.lo mglobal.lo mrestore.lo options.lo \
	precision.lo
mgetc4.obj: constants.obj mfunctions.obj mglobal.obj mrestore.obj options.obj \
	precision.obj
mgetc5.o: constants.o mfunctions.o options.o precision.o
mgetc5.lo: constants.lo mfunctions.lo options.lo precision.lo
mgetc5.obj: constants.obj mfunctions.obj options.obj precision.obj
mgetqs.o: options.o constants.o mfunctions.o mglobal.o precision.o
mgetqs.lo: options.lo constants.lo mfunctions.lo mglobal.lo precision.lo
mgetqs.obj: options.obj constants.obj mfunctions.obj mglobal.obj precision.obj
mglobal.o: precision.o
mglobal.lo: precision.lo
mglobal.obj: precision.obj
mrestore.o: constants.o mfunctions.o precision.o save.o
mrestore.lo: constants.lo mfunctions.lo precision.lo save.lo
mrestore.obj: constants.obj mfunctions.obj precision.obj save.obj
msamurai.o: constants.o ltest.o maccu.o madds.o mgetbase.o mgetc1.o mgetc2.o \
	mgetc3.o mgetc4.o mgetc5.o mgetqs.o mrestore.o mtens.o mtests.o \
	ncuts.o notfirst.o options.o precision.o
msamurai.lo: constants.lo ltest.lo maccu.lo madds.lo mgetbase.lo mgetc1.lo \
	mgetc2.lo mgetc3.lo mgetc4.lo mgetc5.lo mgetqs.lo mrestore.lo \
	mtens.lo mtests.lo ncuts.lo notfirst.lo options.lo precision.lo
msamurai.obj: constants.obj ltest.obj maccu.obj madds.obj mgetbase.obj mgetc1.obj \
	mgetc2.obj mgetc3.obj mgetc4.obj mgetc5.obj mgetqs.obj mrestore.obj \
	mtens.obj mtests.obj ncuts.obj notfirst.obj options.obj precision.obj
mtens.o: constants.o mcgs.o mfunctions.o options.o precision.o
mtens.lo: constants.lo mcgs.lo mfunctions.lo options.lo precision.lo
mtens.obj: constants.obj mcgs.obj mfunctions.obj options.obj precision.obj
mtests.o: constants.o ltest.o mfunctions.o mglobal.o mrestore.o options.o \
	precision.o save.o
mtests.lo: constants.lo ltest.lo mfunctions.lo mglobal.lo mrestore.lo options.lo \
	precision.lo save.lo
mtests.obj: constants.obj ltest.obj mfunctions.obj mglobal.obj mrestore.obj \
	options.obj precision.obj save.obj
save.o: constants.o precision.o
save.lo: constants.lo precision.lo
save.obj: constants.obj precision.obj
