# Module dependencies
inverse_matrice.mod: inverse_matrice.$(OBJEXT)
matrice_s.lo: inverse_matrice.lo
matrice_s.$(OBJEXT): inverse_matrice.$(OBJEXT)
matrice_s.mod: matrice_s.$(OBJEXT) inverse_matrice.$(OBJEXT)
.mod.o:
	@true
