# Module dependencies
adapt_gauss.mod: mod_adapt_gauss.f90 mod_adapt_gauss.$(OBJEXT)
mod_numeric.lo: mod_adapt_gauss.lo
mod_numeric.$(OBJEXT): mod_adapt_gauss.$(OBJEXT)
numerical_evaluation.mod: mod_numeric.f90 mod_numeric.$(OBJEXT) \
	mod_adapt_gauss.$(OBJEXT)
