# Module dependencies
form_factor_higher_ranks.lo: generic_function_np.lo
form_factor_higher_ranks.mod: form_factor_higher_ranks.lo \
	generic_function_np.lo
generic_function_np.mod: generic_function_np.lo
