# Module dependencies
function_3p0m_1mi.mod: function_3p0m_1mi.lo
function_3p1m.lo: mod_h0.lo
function_3p1m.mod: function_3p1m.lo mod_h0.lo
function_3p1m_1mi.lo: mod_he.lo
function_3p1m_1mi.mod: function_3p1m_1mi.lo mod_he.lo
function_3p1m_2mi.lo: mod_gn.lo
function_3p1m_2mi.mod: function_3p1m_2mi.lo mod_gn.lo
function_3p2m.lo: mod_h0.lo mod_he.lo mod_hf.lo
function_3p2m.mod: function_3p2m.lo mod_h0.lo mod_he.lo mod_hf.lo
function_3p2m_1mi.lo: mod_he.lo mod_hf.lo
function_3p2m_1mi.mod: function_3p2m_1mi.lo mod_he.lo mod_hf.lo
function_3p3m.mod: function_3p3m.lo
function_3p_finite.mod: function_3p_finite.lo
generic_function_3p.lo: function_3p0m_1mi.lo function_3p1m.lo \
	function_3p1m_1mi.lo function_3p1m_2mi.lo function_3p2m.lo \
	function_3p2m_1mi.lo function_3p3m.lo function_3p_finite.lo
generic_function_3p.mod: generic_function_3p.lo function_3p0m_1mi.lo \
	function_3p1m.lo function_3p1m_1mi.lo function_3p1m_2mi.lo \
	function_3p2m.lo function_3p2m_1mi.lo function_3p3m.lo \
	function_3p_finite.lo
func_gn.mod: mod_gn.lo
func_h0.mod: mod_h0.lo
func_he.mod: mod_he.lo
func_hf.mod: mod_hf.lo
func_gn.mod: mod_gn.lo
func_hf.mod: mod_hf.lo
func_h0.mod: mod_h0.lo
func_he.mod: mod_he.lo
